name: "GitHub PR Diff checker"
description: "Checks PR body and diff for word occurrences. Can be disabled using a label"
author: "DocPlanner"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  github-token:
    description: "Github token, added magically"
  label-to-skip:
    description: "The name of a label to allow the check to skip"
  diff-not-contain:
    description: "The keyword we are looking for"
  diff-not-contain-count:
    description: "The times the keyword can be mentioned before the check fails"

runs:
  using: "node12"
  main: "dist/index.js"
